### ISSUE TITLE
investigate file browser app for the hub

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#105]
currently the hub doesn't have a GUI file browser; developers can use the workspace tool to do it manually via command line.  perhaps there is a R shiny package that we can add to our current app or offer another app?

**Comment by monaw** [comment]
a quick google search for R Shiny file browser app found nothing.
here's a few possible hub mechanisms:
1. Development Workspace file upload/download
2. use a sftp client to connect to uccommunityhub.hubzero.org
3. Jupyter Notebook has a file browser

**Comment by sinkovit** [comment]
What are the pros/cons of each of these approaches? I'm thinking specifically about difficulty of implementation and ease of use for the gateway users.

**Comment by monaw** [comment]
|    | workspace | sftp | Jupyter Notebook | hub project |
|--|---|--|---|--|
| GUI   | √ | √ if user has a client or else command line | √ | √ |
| upload | √ | 
| download | √ | 
| browse | command line | 
| rename | command line |

**Comment by monaw** [comment]
Bob and i met and we think the hub project mechanism is probably the best way to go...
