### ISSUE TITLE
try move2 package

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#133]

**Comment by matthewwangg** [comment]
This was implemented within the refactor dev branch and now just needs to be merged

**Comment by monaw** [comment]
hi Matthew, just wanted to confirm that the "refectordev" branch is ready and i can merge it with the "dev" branch, then test?

**Comment by sinkovit** [comment]
Hi Mona,

Welcome back from South Africa! I’m looking forward to hearing all about your trip.

Go ahead and merge refactordev with dev and test.

-- Bob

From: MonaW ***@***.***>
Date: Tuesday, June 11, 2024 at 10:28 AM
To: sinkovit/Spatial-ecology ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [sinkovit/Spatial-ecology] try move2 package (Issue #133)

hi Matthew, just wanted to confirm that the "refectordev" branch is ready and i can merge it with the "dev" branch, then test?
