### ISSUE TITLE
Update labels in MKDE (BBMM) tab

### ISSUE THREAD

**Issue by sinkovit** [sinkovit/Spatial-ecology#136]
Update the "MKDE" tab label to "BBMM" and "Variance" to "Local error variance (meters)". See attached figure

![Picture1](https://github.com/sinkovit/Spatial-ecology/assets/5232688/a6126454-c67a-4485-8870-cebc3eeffced)

**Comment by monaw** [comment]
i also updated the display instructions on the right for selecting plot type to:

![Screenshot 2024-04-15 at 11 04 24 AM](https://github.com/sinkovit/Spatial-ecology/assets/18472048/8f297725-cbc1-4321-927e-9d87b88d56e3)
