### ISSUE TITLE
Update labels on MCP tab

### ISSUE THREAD

**Issue by sinkovit** [sinkovit/Spatial-ecology#137]
Update the labels on the MCP tab as shown in figure below
![Picture2](https://github.com/sinkovit/Spatial-ecology/assets/5232688/a4eb6ca5-c694-40ef-add1-e77dd011d0de)

**Comment by monaw** [comment]
![Screenshot 2024-04-15 at 11 26 53 AM](https://github.com/sinkovit/Spatial-ecology/assets/18472048/43e6bb7a-540e-44b8-a3a3-05b52fe232cb)
