### ISSUE TITLE
test & fix refactor merge issues

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#142]
- [x] summary table disappeared!
- [x] data 5_bobcats_F4_F9_F13_M10_M15_BBMMinput.csv MCP plot error: "Error: is.wholenumber(x) || !(0 <= x && x < 2^zoom) is not TRUE"
- [x] data 5_bobcats_F4_F9_F13_M10_M15_BBMMinput.csv BBMM plot crashes and console error "Warning: Error in rep: invalid 'times' argument"
- [x] MCP telemetry points only plot also plots polygon
- [x] seems BBMM plot are not working; keep seeing "Error: unable to plot; please try adjusting the parameter(s) and Plot again..."
- [x] warning about not all contours fit on the map @ https://github.com/sinkovit/Spatial-ecology/blob/7fa185f8bd2212d0e00b6178531462b0625092ba/bin/app.R#L1139 doesn't seem to be showing anymore...it should show for the CondorFull.csv BBMM plot for animal id 269, doesn't matter what the cell size value is but 1000 is a good number to use for testing)
- [x] km2 area calculation is wrong (ie 2481.3065 ha should be 24.813065 km2, not 24813065 km2)

**Comment by matthewwangg** [comment]
I think one of the merges removed the return statement from animalAttributes function within the compute.R file and that might be the reason behind the issue

**Comment by matthewwangg** [comment]
Looks like that change returns the table and fixes the second issue, can't recreate the third issue

**Comment by matthewwangg** [comment]
Looks like my branch was using a variable that was renamed for dev branch, so updating that seems to have fixed the last issue. Updated the code for my refactordev branch

**Comment by monaw** [comment]
yes that seemed to have fixed the 5th issue, thanks again Matthew!

**Comment by monaw** [comment]
@matthewwangg , previously in createContour(), there was a check to see whether the contour fits on the map (see https://github.com/sinkovit/Spatial-ecology/blob/a79ee4cb0e38f6bb1cd66fe372d670db7de9b1ef/bin/compute.R#L256), that check seems to be missing in the new refactor code.  can you figure out how to add that?

**Comment by matthewwangg** [comment]
Updated the information about fits and it seems to display now on the mentioned case, however the tolerance value might need to be adjusted

**Comment by monaw** [comment]
in the [previous code by Bob](https://github.com/sinkovit/Spatial-ecology/blob/a79ee4cb0e38f6bb1cd66fe372d670db7de9b1ef/bin/compute.R#L256), the if-test was a bit different and it didn't use a tolerance check.  could you explain the need for tolerance in the refactored code?

**Comment by matthewwangg** [comment]
Without a tolerance check, the message will always display. The values never matched up exactly on the new object so the tolerance value allows to be able to distinguish between the two cases.

**Comment by monaw** [comment]
note, i tried replacing:
`if (abs(x1[1] - x1[length(x1)]) > tolerance || abs(y1[1] - y1[length(y1)]) > tolerance) {`
with:
`if (x1[1] != x1[length(x1)] && y1[1] != y1[length(y1)]) {`
and sure enough, it doesn't work.
