### ISSUE TITLE
add additional fields for user account requests

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#150]
- [x] set user account registration to require admin approval to avoid spambots creating junk accounts (recommended by Hubzero)

add these additional fields to user account requests:
- [x] first name
- [x] last name
- [x] email address
- [x] institution
- [x] briefly tell us why you want to use our gateway

**Comment by monaw** [comment]
@sinkovit , ok i've added a few more required fields to the user registration.  please take a look [here](https://uccommunityhub.hubzero.org/register).  Note we can change the options for the main reason, gender and racial questions...

**Comment by sinkovit** [comment]
Hi Mona,

In addition to the previous questions, ask the gender and race questions in the attached image. You can modify the text to say

"The Space Use Ecology Gateway is funded by the National Science Foundation (NSF). The following information is entirely voluntary and is used to improve our programs and provide services to a more diverse audience. We also report this information in aggregate (meaning without connecting this with you) to the NSF."

![image](https://github.com/user-attachments/assets/4bc9408d-e13c-4eeb-a7d5-17f4900d7087)

**Comment by monaw** [comment]
hi Bob, I see the word "voluntary" so which ones are NOT required?  I presume the rest are required field?

**Comment by monaw** [comment]
Ilya @ Hubzero made some of the changes and pointed out a couple of issues: 
![Screenshot 2024-08-02 at 7 44 14 PM](https://github.com/user-attachments/assets/d8c02f14-7be8-4011-977e-d1906bd37000)

**Comment by sinkovit** [comment]
Hi Mona, 

Keep first name, last name, email, institution and "briefly tell us why you want to use our gateway" as mandatory. 

Let's also make gender and race voluntary although we have a "Do not wish to provide" option. 

I'm assuming that the "Do not **_with_** to provide" was a typo, so just go ahead and fix that.

Once you or Ilya have made these changes, go ahead and close this issue.

**Comment by monaw** [comment]
@sinkovit , what about the country field, currently it is required but listed under the "voluntary" section...

**Comment by monaw** [comment]
country field is required and moved into the required section of the user registration page @ https://uccommunityhub.hubzero.org/register

**Comment by monaw** [comment]
Ilya made the final fix
