### ISSUE TITLE
BBMM plot problem

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#153]
In the new refactored code, BBMM plotting **without map** looks wrong (from refactordev/dev):

![Screenshot 2024-07-26 at 5 27 03 PM](https://github.com/user-attachments/assets/87b8d253-b8cc-4506-886f-e164cda49916)

same data plots fine currently in our gateway:

![Screenshot 2024-07-26 at 5 26 37 PM](https://github.com/user-attachments/assets/5d316e0c-80fe-49fd-a991-29c6e686bb5a)

**with map** plots fine for the same data:

![Screenshot 2024-07-26 at 5 32 43 PM](https://github.com/user-attachments/assets/a776c361-74d4-4300-99af-82df6adc6dba)

**Comment by matthewwangg** [comment]
Which dataset is having this issue? I can look into this

**Comment by monaw** [comment]
thanks Matthew!  It is the 5_bobcats_F4_F9_F13_M10_M15_BBMMinput.csv data set.  let me know if you don't have it...

**Comment by matthewwangg** [comment]
An update to this issue, I made a change in approach and that seemed to fix the issue. I will update the visuals before adding my code to the refactordev branch so that it looks as intended.

**Comment by sinkovit** [comment]
Hi Matt - welcome back! I was just looking at this issue and was going to dig into what was causing the problem. Once you've updated your refactordev branch, I'll use that to look into issue #154

**Comment by matthewwangg** [comment]
Hey Bob, thanks! I have just committed the changes and I won't close the issue yet, but my changes seemed to resolve the plotting without a map issue at least within my testing.

**Comment by monaw** [comment]
hi @matthewwangg, i tested your commit and it fixed the problem, thank you!  i'm closing this issue...
