### ISSUE TITLE
BBMM fits seems not quite right

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#154]
For the attached dataset, the createContour() fits variable gets set to FALSE currently but in the pre-refactor version (currently available in the gateway), fits is TRUE for that dataset.

This may be related to the [previous fits issue you fixed](https://github.com/sinkovit/Spatial-ecology/issues/142#issuecomment-2211962351)?

[condor.txt](https://github.com/user-attachments/files/16666844/condor.txt)

**Comment by matthewwangg** [comment]
This is likely due to the tolerance that was set up, it may need to be adjusted. I will look into if this would work or if it this functionality requires a different kind of check now

**Comment by monaw** [comment]
@matthewwangg, the problem shows up when cell size = 1000 and buffer = 10000 and for some other values but not for cell size = 100 and buffer = 1000 (actually this should be fits = FALSE but looks like it is TRUE?)

**Comment by matthewwangg** [comment]
I fixed this issue, closing now because for every test case I have access to, the plot warning message matches up for the existing gateway version and the refactordev branch version
