### ISSUE TITLE
Add plotting aspect ratio

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#25]

**Comment by sinkovit** [comment]
Mona - I'm going to reassign this to you since I'm having problems with the version in the dev branch. Pretty easy fix, just replace this

`plotMKDE (rasters[[1]], probs = probs)`

with this

`plotMKDE (rasters[[1]], probs = probs, asp = rasters[[1]]$ny/rasters[[1]]$nx)`

**Comment by monaw** [comment]
thanks Bob, it seems to be working for the Condor data...

before 
![Screen Shot 2022-10-10 at 3 05 52 PM](https://user-images.githubusercontent.com/18472048/194959815-4ec9d781-d6bd-43f8-a9b3-b2638df63afc.png)

after 
![Screen Shot 2022-10-10 at 3 07 59 PM](https://user-images.githubusercontent.com/18472048/194959833-5e55482b-4b36-4976-bdbf-a41260537d4e.png)
