### ISSUE TITLE
Save rasters to a file

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#29]
- [ ] Bob talk to Jesse & figure out which format we should provide

filename should be <animal><id>.<format>

**Comment by monaw** [comment]
use writeRaster function

**Comment by monaw** [comment]
geotiff, ascii format?
Bob will work on writing the raster files & shape files (5-6 files, .dbx, .shape)
shape file based on Jesse's code (sp is being replaced)

**Comment by monaw** [comment]
From Bob on Slack:

After doing some exploring, I discovered that the code you need to write the rasters and shape files already exists (commented out) in the file compute.R, function createContour().
You'll just need to connect to buttons so that the files are written out. The following block writes out the raster file
```
# # Create raster of contours
 # raster.contour <- rasterToContour(rst.mkde, levels = cont$threshold)
 # proj4string(raster.contour) = CRS(crsstr)
 # writeRaster(rst.cont, filename, format = "ascii", overwrite = T)
```
And this block writes the shape files.
```
# # Create shapefiles of contours
 # raster.contour = spChFIDs(raster.contour, paste(contour_probs, "% Contour Line", sep=""))
 # proj4string(raster.contour) = CRS(crsstr)
 # shapefile(x = raster.contour, file = filename, overwrite = T)
```
Note that writing the raster creates a single file (e.g., condor.asc) while the shape files creates a set of five files (e.g., condor_[allcountour|outercontour].[cpg, dbf, prj, shp, shx).
I committed one minor change to the dev branch so that we use just the basename, without [_allcountour|outercontour], which only makes sense for shape files. (edited)

**Comment by monaw** [comment]
@sinkovit, so both raster and shape files are output of MKDE plotting only, not the MCP plot right?

**Comment by sinkovit** [comment]
Yes, they are both output from MKDE. We don’t have any output for the MCP and it’s currently being used only for getting an overview of the data.

From: MonaW ***@***.***>
Date: Friday, June 23, 2023 at 6:40 PM
To: sinkovit/Spatial-ecology ***@***.***>
Cc: Sinkovits, Robert ***@***.***>, Mention ***@***.***>
Subject: Re: [sinkovit/Spatial-ecology] Save rasters to a file (Issue #29)

@sinkovit<https://urldefense.com/v3/__https:/github.com/sinkovit__;!!Mih3wA!DP44e0ScyscUX88ItebPZomIlc1LBY8Y0BpdND8fTB7C5gkX4RA2nl6K45kQy4U0VIGzZy9L5AXLAIfXgGagywlx$>, so both raster and shape files are output of MKDE plotting only, not the MCP plot right?

**Comment by sinkovit** [comment]
That is correct. They are both output from MKDE. We don’t have any output for the MCP and it’s currently being used only for getting an overview of the data.
