### ISSUE TITLE
Managing UTM zones

### ISSUE THREAD

**Issue by sinkovit** [sinkovit/Spatial-ecology#48]
Function preprocessDataframe() in processDataframe.R now returns a list of UTM zones found in input file or inferred from the lat/long data as the third return value.

Because of of the weird way R handles return values and the fact that UTM zones may contain unnecessary and redundant North/South information, I created a utility function (cleanUTMZones in cleanUTMZones.R) that processes the 3rd return value from preprocessDataframe() to get rid of these characters, convert to integers and create a proper list. Suggested usage below

return.values <- preprocessDataframe(gpsdata)
zones <- cleanUTMZones(return.values[3])

When integrating, test that

(1) preprocessDataframe() only returns one value

(2) If UTM zone entered in GUI, compare with what is found in file

These modifications have been made to dev branch

**Comment by monaw** [comment]
@sinkovit, i don't see a call to cleanUTMZones in our current dev code; does this still need to be done?

**Comment by sinkovit** [comment]
Good catch! I had forgotten all about that. We don't need that file/function.
