### ISSUE TITLE
Test MCP point display in dev3

### ISSUE THREAD

**Issue by sinkovit** [sinkovit/Spatial-ecology#56]
I made one small change to minConvexPolygon() to get it to work correctly after upgrading R, RStudio and packages.

mymap <- ggmap(mybasemap) +
    geom_point(data = gpsdata.geo, 
               aes(**_x = coords.x1, y = coords.x2_**, colour = id), size = 0.8, alpha = 0.5)  +
    theme(legend.position = c(-0.2, 0.90)) +
    labs(x = "Longitude", y = "Latitude")

Please test in your R installation and if everything is still working in your end please merge into dev

**Comment by monaw** [comment]
@sinkovit - i just saw this issue; is it still valid?  looks like currently our code is:

```
  # Plot data points on basemap
  mymap <- ggmap(mybasemap) +
    geom_point(data = gpsdata.geo, 
               aes(x = xdata, y = ydata, colour = id), size = 0.8, alpha = 0.5)  +
    theme(legend.position = c(-0.2, 0.90)) +
    labs(x = "Longitude", y = "Latitude")
```

which one is correct?
