### ISSUE TITLE
problem loading James lions dataset

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#66]
James reported that he tried to load his lions dataset from Movebank (study id 2931070090) and the app doesn't seem to do anything.

**Comment by monaw** [comment]
after some debugging, there appears to be 2 issues:

1. as.POSIXct() threw an error and doesn't seem to be able to handle the data time format (eg "9/23/05 22:15") so i replaced it with the call to as.POSIXlt() and specified the format
1. the file size exceeds Shiny's max size which is 5 MB, according to https://groups.google.com/g/shiny-discuss/c/rU3vwGMZexQ/m/zeKhiYXrtEQJ, and James' dataset is > 17 MB so i added options() call to increase the size to 30 MB

**Comment by sinkovit** [comment]
Adding options(shiny.maxRequestSize=30*1024^2) should fix James' problem

**Comment by monaw** [comment]
above problem fixed but now new problem...
loading James' entire lion data set, current we are getting the error message "Error : figure margins too large".  i did some debugging and the error message is coming from the call "area_mcp <- mcp.area(gpsdata.sp, unin="m", unout=areaUnits, percent=100)"

**Comment by sinkovit** [comment]
The default is for function mcp.area() to plot the MCP. Since we only need the results of the area calculation, we can just disable plotting as follows (note last argument)

area_mcp <- mcp.area(gpsdata.sp, unin="m", unout=areaUnits, percent=100, plotit=FALSE)

**Comment by monaw** [comment]
hi @sinkovit , the error for animal F121 is:
`Error in cut.default(getValues(x), breaks = breaks, labels = FALSE, ...): 'breaks' are not unique\n"`

**Comment by sinkovit** [comment]
@monaw I'm not having problem with F121, either when loading either the entire lion data set of restricting to just those records for animal F121. Is this happening at the loading, MCP or MKDE step? And if MCP or MKDE, can you give the parameters?

If I can't reproduce the error, I'll also ask for the data file you're using. Maybe there's something wrong with your file and not mine.
